---
title: "Agroforestry Fiche Refinement"
subtitle: "Prepared for Defra project *Clean Growth through Sustainable Intensification*"
author: "Dr Alasdair Sykes"
date: "28/07/2020"
output: html_document
bibliography: /Users/alasdair/Documents/bibtex-and-csl/library.bib
csl: /Users/alasdair/Documents/bibtex-and-csl/styles-master/elsevier-harvard2.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 1. Overview
This document comprises a refinement to the agroforestry fiche submitted to the Defra Clean Growth through Sustainable Intensification project in June 2019. This document details:

1. Salient elements of the original model
2. Feedback and requests for refinement made in response to the original fiche and model
3. Methods followed to enact corresponding refinements to the model methodology
4. Results from the refined model

### 2. Summary of original fiche
The original agroforestry fiche written for this project summarised the extant literature on agroforestry in the context of GHG abatement, and presented estimated marginal abatement potential and costs for this measure based on a modelled system derived from the literature.

For this original modelled system — and given the wide uncertainties associated with aspects of the measure cost and abatement rates — a Monte Carlo simulated-based uncertainty modelling approach was adopted. The following were considered as a source of uncertainty in the modelled marginal abatement cost:

1. Below-ground C sequestration. Minimum and maximum values for the ranges reported in Aertsens et al. (2013) were utilised.
2. Biomass C sequestration and timber yield. Uncertainty in the yield classes reported in Matthews et al. (2016) was assumed, and this directly related to uncertainty in biomass C sequestration reported by West & Matthews (2012).
3. Planting and maintenance costs. Burgess et al. (2003) report a range of values for most cost categories; these ranges were used as stochastic variables in the simulation.
4. Timber revenue. Variation in timber yield per tree and per hectare (resulting from uncertainty in yield class) was incorporated into the Whiteman et al. (1991) price curve equation. In addition, the variability in timber price index in the period 1991—2017 was used to derive a stochastic scaling factor for data derived from the price curve, producing a randomly-placed estimate of the relative value of the timber in a fluctuating market.
5. Crop yield impacts. Variability in the yield data reported by Burgess et al. (2005) was used to scale the estimate of the crop yield impact induced by the agroforestry system.

The modelled agroforestry system was assumed, in the original fiche, to be applied in a UK wheat system with a grain yield of 8.4 tonnes ha-1 and a gross margin of £796 ha-1. All one-off costs and revenues were annualised and discounted using a discount rate of 3.5%. A Monte Carlo simulation (10,000 samples, Mersenne seed = 2605) was run to estimate the impact of the defined uncertainties on the marginal abatement cost effectiveness of the specified agroforestry systems.



### References

