---
output: html_document
---

This application allows users to modify and interrogate the agroforestry analyses performed as part of the Defra project *Clean Growth through Sustainable Intensification*. These analyses were designed to assess the implementation cost and greenhouse gas abatement potential of agroforestry systems in the United Kingdom. This panel provides an overview of the application and instructions on its use.

For the purposes of this analysis, the measure 'agroforestry' was broken into four sub-measures. These are:

* **Row planting**. Planting trees for timber in rows throughout agricultural areas, with intercropping and/or livestock production between the rows.

* **Shelter belts**. Planting trees in belts (rectangles of dense woodland) throughout agricultural areas for the purpose of providing shelter from wind and rain, with crop or livestock production occurring between belts. For the purposes of this simulation, it is assumed that these belts are periodically harvested for biomass.

* **Fenceline planting**. Planting trees for timber with similar assumptions to the **row planting** scenario, but using areas of otherwise unplanted fenceline as the space for expansion (rather than planting in the field itself).

* **Hedge expansion**. Expanding existing hedges to parts of the field boundary currently occupied only by fences.


#### Input controls 
Each of these four sub-measures has its own set of inputs which may be modified by the user; the controls for these inputs are located in the left-hand sidebar. To improve performance, the app does not automatically update when an input is changed; the user may change multiple inputs, and subsequently use an action button to prompt the server to re-run the simulation and update the app.

There are separate *update* buttons for each of the four sub-measures to support individual changes; these are found in the respective input panels for each measure. There is also a universal *update* button under the **Global options** panel; whenever this is used, all of the simulations in the application are re-calculated.

#### Outputs 
Outputs are displayed in the main panel. Each of the four sub-measures has its own panel, with outputs specific to that simulation displayed. In addition, the app contains an **Aggregated output** panel, which displays combined data for all of the four sub-measures together.

&nbsp;
<hr />
<p style="text-align: center;">App and analysis by <a href="http://www.alasdairsykes.me">Alasdair Sykes</a></p>
<p style="text-align: center;"> <a href="https://github.com/aj-sykes92/agroforestry-defra-prelim">Source code here</a></p>
<p style="text-align: center;"><span style="color: #808080;"><em>alasdair.sykes@sruc.ac.uk</em></span></p>

<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- Add font awesome icons -->
<p style="text-align: center;">
    <a href="https://twitter.com/alasdair_sykes" class="fa fa-twitter"></a>
    <a href="https://www.linkedin.com/in/alasdair-sykes-1b81435a/" class="fa fa-linkedin"></a>
    <a href="https://github.com/aj-sykes92/" class="fa fa-github"></a>
</p>
<hr />

&nbsp;
